- name: Create Controller Nodes
  import_playbook: create-controllers.yaml
  tags:
    - create-controllers

- name: Create Compute Nodes
  import_playbook: create-computes.yaml
  tags:
    - create-computes

- name: Create Ceph Nodes
  import_playbook: create-ceph.yaml
  tags:
    - create-ceph
  when:
    - ceph_external != "1"

- name:  Build VBMC for Overcloud Nodes
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Create Virtual BMC
    shell: |
      count=12
      for I in {{ all_n }}; do
         vbmc add $I --address 192.168.201.${count} --username admin --password "{{ secure_password }}"
         vbmc start $I
         count=$((count+1))
      done
