- name:  Add hypervisor host in inventory
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add all hypervisor group-host
    add_host:
      name: "{{ item.hypervisor_name }}"
      ansible_ssh_user: "{{ item.hypervisor_user }}"
      ansible_ssh_private_key_file: "{{ item.hypervisor_ssh_key }}"
      groups:
        - hypervisor_host
    with_items: "{{ undercloud_nodes }}"
    when: item.hypervisor_name != "localhost"

- name:  Add Undercloud VM/Node
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add undercloud group-host
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ item.hypervisor_user }}@{{ item.hypervisor_name }}"'
      groups:
        - undercloud
    when: item.hypervisor_name != "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

  - name: Add undercloud group-host for localhost hypervisor
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
      groups:
        - undercloud
    when: item.hypervisor_name == "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

- name: Validating the post-upgrade functionality
  hosts: undercloud
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Validating the post-upgrade functionality
    shell: |
      source ~/stackrc
      openstack tripleo validator run --group post-upgrade 2>&1 | tee -a /home/stack/logs/osp16_openstack_tripleo_validator_run_post-upgrade_$(date +%Y-%m-%d-%H%M).log

  - name: Check if pre-upgrade validator has at least one FAILED validator
    shell: |
      VALIDATOR_LOG=$(ls /home/stack/logs/osp16_openstack_tripleo_validator_run_post-upgrade_* | tail -n1)
      egrep 'FAILED|UUID|^\+' ${VALIDATOR_LOG}
    register: failed_validator

  - name: Print failed validator
    debug:
      var: failed_validator.stdout_lines

  - name: Pause to check failed validator
    pause: prompt='Are there any validators in FAILED??? (openstack tripleo validator show run --full <UUID>) Press return to continue. Press Ctrl+c and then "a" to abort'

