- name:  Add hypervisor host in inventory
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add all hypervisor group-host
    add_host:
      name: "{{ item.hypervisor_name }}"
      ansible_ssh_user: "{{ item.hypervisor_user }}"
      ansible_ssh_private_key_file: "{{ item.hypervisor_ssh_key }}"
      groups:
        - hypervisor_host
    with_items: "{{ undercloud_nodes }}"
    when: item.hypervisor_name != "localhost"

- name:  Add Undercloud VM/Node
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add undercloud group-host
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ item.hypervisor_user }}@{{ item.hypervisor_name }}"'
      groups:
        - undercloud
    when: item.hypervisor_name != "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

  - name: Add undercloud group-host for localhost hypervisor
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
      groups:
        - undercloud
    when: item.hypervisor_name == "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

- name: Upgrading to Ceph Storage 4
  hosts: undercloud
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Ensure rhceph-4-tools-for-rhel-8-x86_64-rpms repo is enabled
    shell: |
      sudo subscription-manager repos --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms

  - name: Install ceph-ansible
    shell: |
      sudo dnf install -y ceph-ansible

  - name: Create the script for ceph tag
    copy:
      dest: /home/stack/osp16_openstack_overcloud_external-upgrade_ceph.sh
      owner: stack
      group: stack
      mode: 0755
      content: |
        source /home/stack/stackrc
        openstack overcloud external-upgrade run --stack overcloud --tags ceph 2>&1 | tee -a /home/stack/logs/osp16_openstack_overcloud_external-upgrade_ceph-$(date +%Y-%m-%d-%H%M).log

  - name: messages for debug
    debug:
      msg:
        - "################# RUN TMUX ##################"
        - "# tmux"
        - "# su - stack"
        - "$ cd /home/stack"
        - "$ /home/stack/osp16_openstack_overcloud_external-upgrade_ceph.sh"

  - name: Pause to run playbook
    pause: prompt='Did you run the /home/stack/osp16_openstack_overcloud_external-upgrade_ceph.sh script??? Press return to continue. Press Ctrl+c and then "a" to abort'

  - name: Enable autoscale
    shell: |
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set metrics pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set images pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set backups pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set vms pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set volumes pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set .rgw.root pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set default.rgw.control pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set default.rgw.meta pg_autoscale_mode on '
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph osd pool set default.rgw.log pg_autoscale_mode on '

  - name: Disable auth_allow_insecure_global_id_reclaim
    shell: |
      ansible -m shell controller-1 -i /home/stack/inventory.yaml -b -a 'podman exec ceph-mon-controller-1 ceph config set mon auth_allow_insecure_global_id_reclaim false '
