- name:  Add hypervisor host in inventory
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add all hypervisor group-host
    add_host:
      name: "{{ item.hypervisor_name }}"
      ansible_ssh_user: "{{ item.hypervisor_user }}"
      ansible_ssh_private_key_file: "{{ item.hypervisor_ssh_key }}"
      groups:
        - hypervisor_host
    with_items: "{{ undercloud_nodes }}"
    when: item.hypervisor_name != "localhost"

- name:  Add Undercloud VM/Node
  hosts: localhost
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Add undercloud group-host
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand="ssh -W %h:%p -q {{ item.hypervisor_user }}@{{ item.hypervisor_name }}"'
      groups:
        - undercloud
    when: item.hypervisor_name != "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

  - name: Add undercloud group-host for localhost hypervisor
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_pass: "{{ secure_password }}"
      ansible_ssh_user: stack
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null '
      groups:
        - undercloud
    when: item.hypervisor_name == "localhost"
    with_items:
      - "{{ undercloud_nodes }}"

- name: Template refactor
  hosts: undercloud
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Update new roles_data.yaml
    template:
      src: ansible-templates/home/stack/templates/environments/osp16_roles_data.yaml
      dest: /home/stack/templates/environments/roles_data.yaml
      owner: stack
      group: stack
      mode: 0644
  
  - name: Remove OS::TripleO::NodeTLSData
    shell: |
      cp /home/stack/templates/environments/40-enable-tls.yaml /home/stack/templates/environments/40-enable-tls.yaml.preffu-$(date +%Y-%m-%d-%H%M)
      sed -i -e 's/^resource_registry:.*//g' -e 's/  OS::TripleO::NodeTLSData:.*//g' /home/stack/templates/environments/40-enable-tls.yaml

  - name: Get UC name
    shell: |
      sudo hiera container_image_prepare_node_names | sed -e 's/\[\"//g' -e 's/\"\]//g'
    register: uc_name

  - name: Print UC name
    debug:
      var: uc_name.stdout

  - name: Configuring access to the undercloud registry
    blockinfile:
      path: /home/stack/containers-prepare-parameter.yaml
      backup: True
      insertafter: "^parameter_defaults:"
      marker: "# {mark} ANSIBLE MANAGED BLOCK - ACCESS TO UC"
      block: |2
          DockerInsecureRegistryAddress:
          - {{ uc_name.stdout }}:8787
          - {{ undercloud_ip_prv }}:8787

  - name: Enable rhceph-4-tools-for-rhel-8-x86_64-rpms repo
    shell: |
      sudo subscription-manager repos --enable=rhceph-4-tools-for-rhel-8-x86_64-rpms

  - name: Check Ceph health
    shell: |
      ansible -m shell Controller[0] -i /home/stack/inventory.yaml -b -a 'ceph health | grep HEALTH_OK' -o

  - name: Copy update-nic-templates.sh script
    template:
      src: ansible-templates/home/stack/update-nic-templates.sh
      dest: /home/stack/update-nic-templates.sh
      owner: stack
      group: stack
      mode: 0755

  - name: Execute update-nic-templates.sh
    shell: |
      source /home/stack/stackrc
      /home/stack/update-nic-templates.sh 2>&1 | tee -a /home/stack/logs/osp16_oc_update-nic-templates.sh-$(date +%Y-%m-%d-%H%M).log
    register: update_nic

  - name: Print update-nic-templates.sh output
    debug:
      var: update_nic.stdout_lines

  - name: Pause to check update-nic-templates.sh output
    pause: prompt='Was the update-nic-templates.sh execution successful??? Press return to continue. Press Ctrl+c and then "a" to abort'

  - name: Copy 65-kernelargs.yaml template
    template:
      src: ansible-templates/home/stack/templates/environments/osp16_65-kernelargs.yaml
      dest: /home/stack/templates/environments/65-kernelargs.yaml
      owner: stack
      group: stack
      mode: 0644
      backup: True

  - name: Copy new overcloud-deploy.sh
    template:
      src: ansible-templates/home/stack/osp16_overcloud-deploy.sh
      dest: /home/stack/overcloud-deploy.sh
      mode: 0755
      backup: True
