- name:  Add Undercloud VM/Node
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Add undercloud group-host
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_private_key_file: ansible-ssh/id_rsa
      ansible_ssh_user: stack
      groups:
        - undercloud

- name:  Install Overcloud
  hosts: undercloud
  vars_files:
    - variables.yaml
  tasks:
  - name: Backup containter templates
    shell: |
      DATE=$(date +%Y%m%d-%H%M%S)
      cp -p -f /home/stack/templates/container-images.yaml /home/stack/templates/container-images.yaml.${DATE}
      cp -p -f /home/stack/templates/docker-registry.yaml /home/stack/templates/docker-registry.yaml.${DATE}

  - name: Configure local container registry
    shell: |
      source /home/stack/stackrc
      openstack overcloud container image prepare \
        --output-images-file /home/stack/templates/container-images.yaml \
        --namespace=registry.access.redhat.com/rhosp{{ osp_version }} \
        --set ceph_namespace=registry.access.redhat.com/rhceph \
        --push-destination {{ undercloud_ip_prv }}:8787 \
        --set ceph_image=rhceph-3-rhel7 \
        --tag-from-label {version}-{release} \
        --output-env-file /home/stack/templates/docker-registry.yaml \
        -r /home/stack/templates/osp-13/roles_data.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/ceph-ansible/ceph-ansible.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/network-isolation.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/tls-endpoints-public-ip.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/octavia.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/services/barbican.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/barbican-backend-simple-crypto.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/services-docker/manila.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/services/ironic.yaml \
        -e /usr/share/openstack-tripleo-heat-templates/environments/metrics-collectd-qdr.yaml \
        -e /home/stack/templates/environments/25-hostname-map.yaml \
        -e /home/stack/templates/environments/30-fixed-ip-vips.yaml \
        -e /home/stack/templates/environments/40-enable-tls.yaml \
        -e /home/stack/templates/environments/45-inject-trust-anchor.yaml \
        -e /home/stack/templates/environments/35-ceph-config.yaml \
        -e /home/stack/templates/environments/55-rsvd_host_memory.yaml \
        -e /home/stack/templates/environments/configure-barbican.yaml \
        -e /home/stack/templates/environments/global-config.yaml
    async: 7200
    poll: 10

  - name: Download container images
    shell: |
      sudo openstack overcloud container image upload \
        --verbose --config-file /home/stack/templates/container-images.yaml

  #- name: Remove versionlock
  #  shell: |
  #    yum versionlock clear
  #    yum clean all
  #  become: True

  - name: Updating python-tripleoclient
    yum:
      name: python-tripleoclient
      state: latest
    become: True

  - name: messages for debug
    debug:
      msg:
        - "################# RUN TMUX ##################"
        - "# tmux"
        - "# su - stack"
        - "$ cd /home/stack"
        - "$ openstack undercloud upgrade"

  - name: Pause to run playbook
    pause: prompt='Did you run the openstack undercloud upgrade command??? Press return to continue. Press Ctrl+c and then "a" to abort'

  - name: Reboot the undercloud
    reboot:
    become: True

  #FIXME: improves the undecloud rhosp's services check (nova, neutron...)
  - name: Wait a fixed time for rhosp services to be up
    pause:
      seconds: 120

  - name: Delete images directory
    file:
      path: /home/stack/images
      state: absent

  - name: Create images directory
    file:
      path: /home/stack/images
      state: directory

  - name: Unarchive images
    unarchive:
      src: "{{ item }}"
      dest: /home/stack/images
      remote_src: True
    with_items:
      - /usr/share/rhosp-director-images/overcloud-full-latest-13.0.tar
      - /usr/share/rhosp-director-images/ironic-python-agent-latest-13.0.tar

  - name: Set root password on the image
    shell: |
      virt-customize -a /home/stack/images/overcloud-full.qcow2 --root-password password:{{ secure_password }}

  - name: Upload Overcloud Images to Undercloud Glance.
    shell: |
      source /home/stack/stackrc
      openstack overcloud image upload --update-existing --image-path /home/stack/images/

  - name: Configure nodes to use new images
    shell: |
      source /home/stack/stackrc
      openstack overcloud node configure $(openstack baremetal node list -c UUID -f value)
