- name:  Prepare Various Images required for Installation
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Copying RHEL-7 Image from web to images dir
    get_url:
      url: "{{ image_location }}"
      dest: "{{ image_dir }}/{{ item }}.qcow2"
      mode: '0660'
      owner: root
      group: root
    with_items: "{{ supported_os }}"

  - name: Create a new 100GB Blank Image
    shell: |
      qemu-img create -f qcow2  {{ image_dir }}/{{ item }}-100G.qcow2 100G
    with_items: "{{ supported_os }}"

  - name: Resizing the filesystem to 100G
    shell: |
      virt-resize --expand /dev/sda1 {{ image_dir }}/{{ item }}.qcow2 {{ image_dir }}/{{ item }}-100G.qcow2
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
    with_items: "{{ supported_os }}"

  - name: Customizing the image to set root password, push ssh key and remove cloud-init
    shell: |
      virt-customize -a {{ image_dir }}/{{ item }}-100G.qcow2 --root-password password:redhat --ssh-inject "root:file:{{ ssh_pub }}" --selinux-relabel --run-command 'yum remove cloud-init* -y'
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
    with_items: "{{ supported_os }}"

- name:  Prepare Undercloud Golden Image for OSP-13
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Copy Base Image to create Undercloud image
    copy:
      src: "{{ image_dir }}/{{ item }}-100G.qcow2"
      dest: "{{ image_dir }}/{{ item }}-undercloud.qcow2"
    with_items: "{{ supported_os }}"

  - name: Create /tmp/ifcfg-eth0 for RHEL7
    copy:
      dest: /tmp/ifcfg-eth0
      content: |
        DEVICE=eth0
        ONBOOT=yes
        IPADDR={{ undercloud_ip }}
        NETMASK=255.255.255.0
        GATEWAY=192.168.201.1
        NM_CONTROLLED=no
        DNS1={{ dns_ip }}

  - name: Create /tmp/ifcfg-eth1 for RHEL7
    copy:
      dest: /tmp/ifcfg-eth1
      content: |
        DEVICE=eth1
        TYPE=Ethernet
        BOOTPROTO=none
        ONBOOT=yes
        NM_CONTROLLED=no

  - name: Create /tmp/ifcfg-eth1.2002 and 2003 for RHEL7
    copy:
      dest: "/tmp/ifcfg-eth1.{{ item.vlanid }}"
      content: |
        DEVICE=eth1.{{ item.vlanid }}
        BOOTPROTO=static
        ONBOOT=yes
        IPADDR=192.168.{{ item.subnet }}.30
        NETMASK=255.255.255.0
        NM_CONTROLLED=no
        VLAN=yes
    with_items:
      - { vlanid: 2002, subnet: 202 }
      - { vlanid: 2003, subnet: 203 }

  - name: Copying Config files to the rhel7 undercloud image
    shell: |
      virt-copy-in -a {{ image_dir }}/rhel7-undercloud.qcow2 /tmp/ifcfg-eth0 /tmp/ifcfg-eth1 /tmp/ifcfg-eth1.2002 /tmp/ifcfg-eth1.2003 /etc/sysconfig/network-scripts/
    environment:
      LIBGUESTFS_PATH: "{{ libguestfs_path }}"
