- name:  Add Undercloud VM/Node
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
  - name: Add undercloud group-host
    add_host:
      name: "{{ undercloud_n }}.{{ domain }}"
      ansible_ssh_private_key_file: ansible-ssh/id_rsa
      ansible_ssh_user: stack
      groups:
        - undercloud

- name: Register OC and set repositories
  hosts: undercloud
  vars_files:
    - variables.yaml
    - overcloud-ansible-nodes.json
  tasks:
  - name: Generate OC ansible inventory
    shell: |
      source /home/stack/stackrc
      tripleo-ansible-inventory --stack overcloud --ansible_ssh_user heat-admin --static-yaml-inventory /home/stack/inventory.yaml

  - name: Registering all overcloud nodes
    shell: |
      ansible -m shell 'all,!Undercloud' -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a 'subscription-manager register --force --username {{ rh_subcription_user }} --password {{ rh_subcription_password }}'
    when:
      - not skip_registration|bool

  - name: Attach poolid
    shell: |
      ansible -m shell 'all,!Undercloud' -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a 'subscription-manager attach --pool={{ rh_subcription_pool }}'
    when:
      - not skip_registration|bool

  - name: Set repository for the controller nodes
    shell: |
      ansible -m shell Controller -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a "subscription-manager repos --disable='*' --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms --enable=rhel-7-server-rhceph-3-tools-rpms --enable=rhel-7-server-rhceph-3-mon-rpms"
    when:
      - osp_version == 13


  - name: Set repository for the compute nodes
    shell: |
      ansible -m shell Compute -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a "subscription-manager repos --disable='*' --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-openstack-13-rpms --enable=rhel-7-server-rhceph-3-tools-rpms"
    when:
      - osp_version == 13

  - name: Set repository for the ceph nodes
    shell: |
      ansible -m shell Compute -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a "subscription-manager repos --disable='*' --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-7-server-openstack-13-rpms --enable=rhel-7-server-rhceph-3-tools-rpms --enable=rhel-7-server-rhceph-3-osd-rpms"
    when:
      - osp_version == 13

  - name: Clean yum cache
    shell: |
      ansible -m shell 'all,!Undercloud' -b -i /home/stack/inventory.yaml  --ssh-extra-args='-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no ' -a "yum clean all"
    when:
      - osp_version == 13

